version: '3.4'
services:

  ## RABBITMQ.
  rabbit:
    image: 'rabbitmq:3.7-management'
    container_name: rabbit
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"


   ## PRODUCTOR
  productor_microservice_php7:
    image: 'geekshubs/geekshubs-php-fpm74'
    container_name: productor_microservice_php7
    depends_on:
      - rabbit
    restart: on-failure
    links: 
      - rabbit
    volumes:
      - ./productor_lumen:/var/www/html
      


   ## CONSUMIDOR
  consumidor_microservice_php7:
    image: 'geekshubs/geekshubs-php-fpm74'
    container_name: consumidor_microservice_php7
    depends_on:
      - rabbit
    restart: on-failure
    links: 
      - rabbit
    volumes:
      - ./consumidor_lumen:/var/www/html
      